#!/bin/bash
# Training script for smolvla_kiroween-potion-v1
# Dataset: jlamperez/kiroween-potion-v1
# Generated by setup_train.py

# Check if CUDA is available
if ! command -v nvidia-smi &> /dev/null; then
    echo "⚠️  Warning: nvidia-smi not found. CUDA may not be available."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Start training
echo "Starting training: smolvla_kiroween-potion-v1"
echo "Dataset: jlamperez/kiroween-potion-v1"
echo "Output: outputs/train/smolvla_kiroween-potion-v1"
echo ""

PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --dataset.repo_id=jlamperez/kiroween-potion-v1 \
  --dataset.image_transforms.enable=true \
  --policy.device=cuda \
  --policy.use_amp=true \
  --policy.n_action_steps=50 \
  --policy.chunk_size=50 \
  --batch_size=16 \
  --steps=20000 \
  --save_checkpoint=true \
  --save_freq=5000 \
  --eval_freq=5000 \
  --wandb.enable=true \
  --output_dir=outputs/train/smolvla_kiroween-potion-v1 \
  --job_name=smolvla_kiroween-potion-v1 \
  --policy.repo_id=jlamperez/test-policy-smolvla \
  --rename_map='{"observation.images.camera1": "observation.images.camera1", "observation.images.camera2": "observation.images.camera2"}'
